image: python:3.6.8

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

test:
  script:
    - pytest -v --ff --tb=no

deploy_production:
  stage: deploy
  environment:
    name: production
  script:
    - ssh ubuntu@ec2-18-222-28-147.us-east-2.compute.amazonaws.com "cd /home/ubuntu/cloud/skills-cloud && pwd && git pull origin master && bash /home/ubuntu/cloud/gun_reload.sh && exit"
  only:
    - master
